### PR TITLE
Serve assets from its own location

### LINKED ISSUE #591: Serve assets from its own location
### Are you reporting a bug?
"No"

### Is this a feature request?
"Yes"

I'd like to be able to separate assets from my views.
Ideally, I want the site to be in its domain and my assets on a CDN, something like this:

www.website.com/page/index.html
assets.website.com/timestamp/{assets go in here}

What I would probably do, is have 2 configurable things:

**REACT_STATIC_ASSET_PATH**
If it exists, instead of putting assets on the root, with would put them on a folder:

`REACT_STATIC_ASSET_PATH='/assets'` would result in this:
www.website.com/page/assets/{css-js-imgs-in-here}

**REACT_STATIC_ASSET_URL**
if it exists, it would make the references to the asset be absolute, to this url.

`REACT_STATIC_ASSET_PATH='/assets'`
`REACT_STATIC_ASSET_URL='https://assets.website.com'`

 would result on this:
assets.website.com/page/assets/{css-js-imgs-in-here}

### PR DESCRIPTION
**Pull request by lottamus**
## Description

https://webpack.js.org/configuration/output/#output-publicpath

Adds option for `config.paths.assets`. This allows you to configure a directory where Webpack will output the bundles assets (JS, CSS, static images, etc).

Right now it will output the webpack bundled files to `{config.paths.dist}/{config.paths.assets}` and rewrite the script/link tags in HTML to be `{publicPath}/{config.paths.assets}`.

For example if you have the following config:
```
"paths": {
  "dist": "build",
  "assets": "assets"
}
```

You will end up with a directory structure like the following
```
/build
  /index.html
  /routeInfo.json
  /assets
    /main.js
    /styles.css
```

index.html will have
```
<script src="/assets/main.js" />
<link rel="stylesheet" href="/assets/styles.css" />
```

## Changes/Tasks
- [x] add option for `config.paths.assets`
- [x] add option for `config.assetsPath` that can be absolute url?
- testing
  - [x] absolute siteRoot
  - [x] basePath
  - [x] disableRoutePrefixing
- docs
  - [x] `config.paths.assets`
  - [x] `config.assetsPath`

## Motivation and Context
1. fixes #591 

## Types of changes
- [x] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Looking good!

**Comment by ricardomccerqueira** [comment]
This is pretty good :)
If you can create an option for the absolute URL I'd say it's perfect.

ps: thanks for doing this.

**Comment by lottamus** [comment]
Yep just thinking about the best way to implement that.

Right now it uses `{config.paths.dist}/{config.paths.assets}` to determine where to output the asset files on disk.

It then uses `{config.siteRoot}/{config.basePath}/{config.paths.assets}` to determine where to fetch the asset files on the client. 

We could introduce a `config.assetsPath` that will be used to override that. This would allow you to set `config.assetsPath = "https://cdn.example.com"` and the client will requests assets from there instead. This is a similar approach to how we are doing `config.paths.dist` and `{config.siteRoot}/{config.basePath}`.

Thoughts?

**Comment by ricardomccerqueira** [comment]
I completely agree.

this is what I had initially suggested ( which is a similar approach to what you're saying ):

REACT_STATIC_ASSET_PATH='/assets'
REACT_STATIC_ASSET_URL='https://assets.website.com'

would result on this:
assets.website.com/page/assets/{css-js-imgs-in-here}

**Comment by tannerlinsley** [comment]
Where are we on this? I like where it's going.

**Comment by ricardomccerqueira** [comment]
Is there any chance this will be merged?

( I'll gladly help if there's anything I can help with )

**Comment by lottamus** [comment]
Sorry I've been out of town the past week. 

Yep it's working fine now but still need to push the code for absolute asset path. I'll have some time this weekend

**Comment by ricardomccerqueira** [comment]
Would you mind if myself or someone else from uSwitch picked this up? 
It's really crucial for us to go live with react-static, so if you don't have the time, I'm sure one of us will be more than happy to continue what you started :)

**Comment by annez** [comment]
We're happy to pick this up if it's easier. Wanting to move all our content to this but this is a blocker going forward without taking that branch and editing it ourselves :)

**Comment by tannerlinsley** [comment]
@annez and others, let's take another look at this. You'll have to sync up with master (which is now on webpack 4)

**Comment by lottamus** [comment]
@ricardomccerqueira @annez @tannerlinsley I've updated this PR with master and included the ability to pass `config.assetsPath` which can be an absolute URL

For example

```
config = {
  assetsPath: "https://assets.example.com",
}
```
Will produce script tags pointing at "https://assets.example.com"

```
config = {
  siteRoot: "https://example.com",
  basePath: "base",
  assetsPath: "foo/bar",
}
```
Will produce script tags pointing at "https://example.com/base/foo/bar"

```
config = {
  siteRoot: "https://example.com",
  basePath: "base",
  paths: {
    root: "path/to/root/dir",
    assets: "foo/bar",
  },
}
```
Will produce script tags pointing at "https://example.com/base/foo/bar" with asset files located at `path/to/root/dir/foo/bar

**Comment by lottamus** [comment]
@tannerlinsley this PR is done and up to date with the latest master changes. Looks like the failing tests are due to the babel 7 upgrade.

**Comment by lottamus** [comment]
Yep! Already using it in production 🚀

**Comment by tannerlinsley** [comment]
Nice!

**Comment by tannerlinsley** [comment]
Looks like some tests are failing. Might need to be fixed, or updated.

To update snapshots, you can run `yarn unitTestWatch` and hit the `u` key if they can safely be updated.

**Comment by lottamus** [comment]
@tannerlinsley fixed!

**Comment by tannerlinsley** [comment]
Merged and published under `6.0.0-beta.14`

**Pull request merged**
