### PR TITLE
WIP: try out lerna for dev

### PR DESCRIPTION
**Pull request by rileylnapier**
set up lerna

so 

```
packages/react-static
packages/example=[[example-name]]
```

to run an example simply 

```
npm i
npm start -- [[example-name]]
npm start -- basic
npm start -- algolia
npm start -- blank

also

npm build -- [[example-name]]
```

this will watch files in react-static and start dev-server for said example.

i'm sure publishing and some documentation workflow might be broken, but figure get some eyes on this to see if you like.

### CODE REVIEW

**Comment by rileylnapier** [comment]
also is nice that all examples will get auto updated to newest react-static version.  unless specifically locked to old version.

**Comment by rileylnapier** [comment]
if this doesn't work out, and yarn-link is better approach.  

we should create a "how to contribute" doc.  so people (including myself) know the best development processes

**Comment by severen** [comment]
>if this doesn't work out, and yarn-link is better approach.

You can actually have Lerna use that 😉.

**Comment by rileylnapier** [comment]
@severen you mean have lerna use yarn workspaces?

**Comment by severen** [comment]
Yes, see [here](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/#integrating-with-lerna
).

**Comment by tannerlinsley** [comment]
Let's stick with the exiting contribution workflow for now.

**Comment by rileylnapier** [comment]
Sounds good amigo!!

**Pull request closed without merging**
