### PR TITLE
[FIX] SASS build fixed, Universal updates

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
## Description
Your build toolchain will now work correctly with my plugin. 
@tannerlinsley thanks for helping me debug this

This fixes a long standing issue inherited from webpacks mini-css. you can read about the fix here:
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/104

## Changes/Tasks

- [x] Updated locks and dependencies

## Motivation and Context

Passing builds are important 😂 

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Ive noticed alot of random versions of my software in your yarn locks. Sometimes new versions do not get installed and i have to force install them. 

It might be a good idea to look at adding a recursive function that can apply updates to the lock files by re-running `yarn --force or update`

**Comment by ScriptedAlchemy** [comment]
Build erros appear unrelated to my changes, or im going crazy

**Comment by tannerlinsley** [comment]
Point your PR to the V6 branch 😉.

**Comment by tannerlinsley** [comment]
RE: lock files: I have a script that does that. I plan on doing a massive relock when we release v6

**Comment by tannerlinsley** [comment]
Crap. Looks like the branch swap didn't go nicely (usually does). Can you open a new PR (or rebase against the v6 branch)?

**Comment by ScriptedAlchemy** [comment]
will do

**Pull request closed without merging**
