### PR TITLE
Fixed styled components example for V6

### PR DESCRIPTION
**Pull request by Pixelatex**
## Description
Updated styled comp example to work with v6

## Changes/Tasks
- [*] Changed code

## Motivation and Context
The example was broken

## Types of changes
- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [*] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by sgup** [comment]
`http://localhost:3000/blog` still breaks for me with these changes

image

**Comment by Pixelatex** [comment]
Yup, just noticed I forgot a small bit, creating a second PR to fix it. (code done at 1 am is not my best it seems 😄

**Comment by sgup** [comment]
ok, good luck!

**Comment by Pixelatex** [comment]
there's something wonky with the newer version of the hot reloader. Guessing that there's some missing config. I'll look into it in a few hours (or someone else who is not in need of sleep right now)

**Comment by sgup** [comment]
For sure, get some sleep!

**Pull request merged**
