### PR TITLE
allow progress in non-TTY (and fix testing)

### PR DESCRIPTION
**Pull request by bkniffler**
## Description
react-static with many pages can take a while for certain operations like exporting html. On CI servers, the progress bar will not show since TTY doesn't work. This PR will add a fallback that shows rolling progress.

This PR uses steps of 5% but we can change this.

## Screenshots (if appropriate):
bildschirmfoto 2018-07-13 um 14 55 46

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Love it!

**Comment by bkniffler** [comment]
I've added a commit to fix testing (though not really related to my PR!)

**Comment by bkniffler** [comment]
Okay, builds passing now! 

I'd be happy about an new version publish if you decide to merge :)

**Comment by tannerlinsley** [comment]
6.0.0-beta.12 is now available ;)

**Pull request merged**
