### PR TITLE
[WIP] Add Intersection Observer support to Prefetch component

### PR DESCRIPTION
**Pull request by EmilTholin**
Thank you for your hard work on react-static. I get goosebumps just experimenting with this masterpiece of a project.

This MR adds a new component `PrefetchWhenSeen`, which will fire the prefetch of its path when it is visible in the view. This opens up for powerful techniques like e.g. prefetching a page when the user first sees a link to it:

```javascript
<PrefetchWhenSeen path={`/blog/post/${post.id}/`}>
  <Link to={`/blog/post/${post.id}/`}>{post.title}</Link>
</PrefetchWhenSeen>
```

intersection_observer_prefetch

Is this something you are interested in? The reason why I didn't put a new prop on the `Prefetch` component and add it conditionally that way, is because `Prefetch` has no wrapping element, so I could not put a `ref` on it.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Great work! This is what I like to see :)

**Comment by tannerlinsley** [comment]
Can you please open another PR and add some documentation to the README ? :)

**Comment by EmilTholin** [comment]
Thanks! Absolutely. You would like the additions to the README in a separate MR?

**Comment by tannerlinsley** [comment]
Yes, since I preemptively merged this one already ;)

**Pull request merged**
