### PR TITLE
Add Contenful CMS example

### PR DESCRIPTION
**Pull request by lurnid**
## Description
Added an example of using Contentful CMS with react-static

## Changes/Tasks

- [x] Changed code

## Motivation and Context

Adds an example of using Contentful CMS with react-static

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
It's actually going to be easier if you just check out the v6 branch locally, add your example, then make the PR.

**Comment by tannerlinsley** [comment]
From there I can guide you through the breaking changes (which might not even be any) 😄

**Comment by lurnid** [comment]
Yep, just realised that

**Comment by lurnid** [comment]
Do you want to close this PR and I'll start a new one to keep it tidier?

**Comment by tannerlinsley** [comment]
Actually, I think it's just those routing changes (which tbh aren't required, but they are nice)

**Comment by tannerlinsley** [comment]
Yeah, let's do that.

**Pull request closed without merging**
