### PR TITLE
graphql-request example

### PR DESCRIPTION
**Pull request by hmeissner**
Static blog example using `graphql-request` and GraphCMS as data source.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Fantastic! Let me know when you're ready to merge

**Comment by hmeissner** [comment]
Let me just adjust the styling to pass Travis and we should be good to go!

**Comment by tannerlinsley** [comment]
Excellent!

**Comment by hmeissner** [comment]
`eslint` throws a warning about https://github.com/hmeissner/react-static/blob/master/examples/graphql-request/src/pages/Post.js#L13 with `no-danger`. The `dangerouslySetInnerHTML` is there to parse the content of GraphCMS`s markdown field which is a string with html tags.

To avoid the warning I can throw in an eslint ignore along with a proper explanation of why the `dangerouslySetInnerHTML` is there. Something like this:
```
{/*
  dangerouslySetInnerHTML is here to parse a markdown field from GraphCMS.
  The field contains a string with HTML tags as GraphCMS already does the markdown parsing.
  If you want to avoid dangerouslySetInnerHTML in your project you can use any html/markdown
  parsing plugin for React like https://github.com/rexxars/react-markdown
*/}
<div dangerouslySetInnerHTML={{ __html: post.content }} /> {/* eslint react/no-danger: 0 */}
```

**Comment by tannerlinsley** [comment]
That's more than okay :)

**Pull request merged**
