### PR TITLE
Use style-loader in dev to make sure css hmr works

### PR DESCRIPTION
**Pull request by KidkArolis**
See #783

### CODE REVIEW

**Comment by tannerlinsley** [comment]
@ScriptedAlchemy any ideas on why this would be necessary?

**Comment by ScriptedAlchemy** [comment]
No, I’ll take a look. Likely just needs updated. HMR has been tried and tested, it’s working. I’ll take a look today

**Comment by ScriptedAlchemy** [comment]
We should be able to close this out. @KidkArolis - the fault was with my plugin. Ive merged a pull-request into react-static which fixes this issue.

**Comment by tannerlinsley** [comment]
Go ahead :)

**Pull request closed without merging**
