### PR TITLE
Webpack 4

### PR DESCRIPTION
**Pull request by sudarshang**
Upgrades react-static libray to Webpack 4.

## Changes/Tasks
- [ ] Refactored the existing webpack production config to separate out the static rendering and production bundling
- [ ] Upgraded plugins, loaders and config to webpack 4

## Motivation and Context
Webpack 4 has been out for a while now. Some of the existing packages that react-static uses have been deprecated and are no longer being maintained.

## Types of changes
- [x] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This looks great! Are all of the examples building correctly? Is the code splitting working correctly?

**Comment by sudarshang** [comment]
@tannerlinsley I have only built the examples. I have not yet manually tested them or checked for correct code splitting. What is a good way to test that code splitting is working correctly?

**Comment by sudarshang** [comment]
I have been testing this branch and noticed a major issue. While the build step works the generated html lacks the necessary preloads. See gist [here](https://gist.github.com/sudarshang/34c095a863b62d32f9c21bae4e4f55e3).

**Comment by tannerlinsley** [comment]
What's the latest on this?

**Comment by sudarshang** [comment]
In f6f39c6a403f08ac26badde34a88297a0c10e643 I replaced webpack-flush-chunks with equivalent code that works with webpack-4. Looking at the diff for [index.html](https://gist.github.com/sudarshang/e755e6da670097219065df40ec791758) generated with webpack-4 branch and [index.html](https://gist.github.com/sudarshang/ab654744b2ce9aae23bd757dc28a178e) generated with master branch, the static html generation is correct for the `basic` example.

When I check the page with chrome, there is a difference in the JS files being included. Here is what it looks like for the webpack-4 branch. 
webpack-4-chrome-dev

This is different from the master branch
master-chrome-dev

I have been stuck trying to figure out why we have this difference, any pointers on how these script tags are being generated will be greatly appreciated.

**Comment by poorpaddy** [comment]
@sudarshang it appears they are both loading home, about and blog js files but not in the order or way you'd expect. The second screenshot has the home.js included as a link just under bootstrap. Personally, I don't see a problem with that.

**Comment by sudarshang** [comment]
@poorpaddy I think the problem is not clear from the images I pasted. Here are the scripts from the webpack-4 branch

```
<script charset="utf-8" src="/templates/src/containers/Home.28b8ce34.js">
</script><script charset="utf-8" src="/templates/src/containers/About.ecb37b00.js">
</script><script charset="utf-8" src="/templates/src/containers/Blog.292b8061.js"></script>

```

and here from the master branch

```
<script type="text/javascript" charset="utf-8" async="" src="/templates/src/containers/Blog.16b4aea4.js"></script>
<script type="text/javascript" charset="utf-8" async="" src="/templates/src/containers/About.393ad3ad.js"></script>
```

Since this is the `Home` page we do not need the Blog and About Javascript. On the master these files are correctly being loaded `async`. On the webpack-4 branch all the files are being loaded so I think we are not getting code splitting.

The webpack bootstrap code inserts these script elements in the `head` tag. I am still trying to figure out why there is a difference between master and webpack-4.

**Comment by poorpaddy** [comment]
@sudarshang that is strange. I think that is a function of html-webpack-plugin.

**Comment by poorpaddy** [comment]
/* fake namespace object */ :dizzy_face:

**Comment by zackljackson** [comment]
I’ve got a working solution.  And will be introducing a major update this weekend is time permits. 

This solution fixes the industry wide problem of HMR CSS in webpack 4 

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60#issuecomment-392317314

**Comment by sudarshang** [comment]
I am currently swamped and don't think I can look into this until at least mid-June. Feel free to close this PR and start another one if someone else wants to take this on.

**Comment by zackljackson** [comment]
Pull request open for extract-css-chunks-webpack-plugin

its installable on npm `extract-css-chunks-webpack-plugin@next`

Hope it helps the upgrade effort

**Comment by poorpaddy** [comment]
What's the status on this?

**Comment by sudarshang** [comment]
@poorpaddy I am sorry I have not been able to make progress on this. I hope to get back to this by end of this week

**Comment by ScriptedAlchemy** [comment]
After reading over the thread. Can anyone highlight any issues still remaining?
@sudarshang ?

I'll pull this branch and see if i can help you guys close this issue

**Comment by poorpaddy** [comment]
@ScriptedAlchemy I think its still a matter of checking all the examples to see if they build correctly and are tested for working correctly. Especially testing the code splitting.

**Comment by tannerlinsley** [comment]
I just barely brought it up to speed with the latest webpack-flush-chunks and worked through some bugs. The best way to test is this:

Build the core code:
- `yarn && yarn link && yarn start`

Build the `examples/basic` example
- `yarn && yarn link react-static && yarn start/build`

I'm still seeing some deprecation warnings when running webpack, and we could also use some advice on the best optimization strategy.

**Comment by ScriptedAlchemy** [comment]
Yeah I probs let know what they are.

At the end of the day, I’ve had to upgrade some big infrastructures to WP4.
Likely won’t be anything new :)

I’ll fork this branch and open a pr?

**Comment by tannerlinsley** [comment]
Yeah, that'd be great. 👍

**Comment by ScriptedAlchemy** [comment]
There’s still one last update that needs to go in on my side around RUC, depending on your setup, it might be a good idea for me to install V3 on its @next tag.

**Comment by tannerlinsley** [comment]
Yeah, whatever you think needs to happen. 👍

**Comment by tannerlinsley** [comment]
Closed with different PR. Yay!

**Comment by JustFly1984** [comment]
Is there any guide how to migrate webpack config to new version?

**Comment by tannerlinsley** [comment]
We will provide documentation, or at least links to sufficient
documentation to do so. Stay tuned.

**Pull request closed without merging**
