### PR TITLE
fix: Updated extract-css-chunks to support React Static configurations.

### LINKED ISSUE #783: CSS hot reloading does not work in v6
### Are you reporting a bug?

Yes.

### Environment

1.  `react-static -v`: 6.0.0-beta.21
2.  `node -v`: v10.11.0
3.  `yarn --version or npm -v`: 1.10.1
4.  Operating system: macOS

### Steps to Reproduce the problem

1.  npm i -g react-static@6.0.0-beta.21
2.  react-static create
3.  choose basic
4. yarn start
5. modify app.css

### Expected Behavior

CSS should hot reload, but it doesn't

I've been using react-static@6 beta since 6.0.0-beta.14 and css hot reloading never worked for me.

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
## Description
This addresses an issue where configurations both used `use` and `loader` keys inside of a oneOf array. These complex configurations caused the loader to fail when trying to inject itsself into the build.

Fixes #783

## Changes/Tasks

- [x] Updated Dependency

## Motivation and Context
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/114/files

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
yep, just saw the monorepo :P

**Comment by tannerlinsley** [comment]
😄

**Comment by tannerlinsley** [comment]
Looks like the test site isn't using the linked version. I just pushed some updated travis scripts in v6. Let's see if that fixes it

**Comment by tannerlinsley** [comment]
Yep! We're still figuring out releases and what not.

**Pull request merged**
