### PR TITLE
Use bluebird Promise.map to limit concurrency

### PR DESCRIPTION
**Pull request by lottamus**
This PR demonstrates a possible fix for https://github.com/nozzle/react-static/issues/311.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I love this idea. Any way to do it without bluebird?

**Comment by tannerlinsley** [comment]
I would vote for this module: https://github.com/zeit/async-throttle

**Comment by tannerlinsley** [comment]
Another thing, I would love for the concurrency to be set at a sensible default, but more importantly be customizable via the config.

**Comment by lottamus** [comment]
It looks like that repo was archived in favor of https://github.com/zeit/async-sema. I also found https://github.com/timdp/es6-promise-pool.

I will add an option to the config to set the concurrency limit. Do you have a suggestion on the default value?

**Comment by tannerlinsley** [comment]
Try 8 for now

**Comment by tannerlinsley** [comment]
FYI, I'm actually building a pooling and throttling mechanism right now. We can probably just use that :)

**Comment by tannerlinsley** [comment]
Oops

**Comment by lottamus** [comment]
Nice! Shoot it over to me when you're done. 

Do you think we should enforce these limits on all the `Promise.all` calls? I was only running out of memory with https://github.com/nozzle/react-static/blob/master/src/static.js#L106, but I could see others that handle writing files could pose an issue too: https://github.com/nozzle/react-static/blob/master/src/static.js#L61 and https://github.com/nozzle/react-static/blob/master/src/static.js#L89

**Comment by tannerlinsley** [comment]
Almost done :) And yes, possibly, but I say we hold off until it becomes a problem first and avoid the pre-op :)

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/swimmer :)

**Comment by tannerlinsley** [comment]
Any progress here? I've added the swimmer library to master and I'm using it in the client to throttle requests

**Comment by lottamus** [comment]
Closing in favor of #325

**Pull request closed without merging**
