### PR TITLE
Markdown example

### PR DESCRIPTION
**Pull request by DanWebb**
## Description
Adds a markdown example using [jdown](https://github.com/DanWebb/jdown) which converts a directory of markdown files into JSON in the build stage so that the JSON can be used to populate content on the site with route data. 

## Changes/Tasks

- [x] Added jdown as a dependency
- [x] Populated basic example with posts and page content in markdown
- [x] Updated example readme with real world example and mention of markdown
- [x] Removed axios as it's no longer needed to pull the example content in

## Motivation and Context

I couldn't find a good way (in my opinion) to use React Static with using simple markdown files for content, so I created one. 

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Are you using the the new rebuildRoutes feature to hot reload the markdown data when it changes?

**Comment by DanWebb** [comment]
I've now added hot reloading of the markdown content using `rebuildRoutes`!

**Comment by tannerlinsley** [comment]
Just needs to pass tests now!

**Comment by DanWebb** [comment]
👌Fixed that pesky bracket spacing and builds passing 💪

**Pull request merged**
