### PR TITLE
Add Tailwind CSS example

### PR DESCRIPTION
**Pull request by yuyaohshimo**
Add Tailwind CSS example. Please review/merge.

### CODE REVIEW

**Comment by EmilTholin** [comment]
Hi @yuyaohshimo! This is really cool, but [there already is a Tailwind example](https://github.com/nozzle/react-static/tree/master/examples/glamorous-tailwind). Does that not suit your needs?

**Comment by yuyaohshimo** [comment]
Hi @EmilTholin! I wanted to use Tailwind CSS with Webpack.

**Comment by tannerlinsley** [comment]
Are you saying the current tailwind example isn't implemented correctly?

**Comment by tannerlinsley** [comment]
At the very least, the PR needs to pass linting. Let's get that taken care of.

**Comment by yuyaohshimo** [comment]
>Are you saying the current tailwind example isn't implemented correctly?

No, but I thought the current Tailwind example isn't compiled by Webpack.

>https://github.com/nozzle/react-static/blob/master/examples/glamorous-tailwind/package.json#L10

According to above script, the current Tailwind example is compiled by postcss-cli instead of Webpack:

**Comment by tannerlinsley** [comment]
True

**Comment by yuyaohshimo** [comment]
@tannerlinsley 
I fixed linting in the [commit](https://github.com/nozzle/react-static/pull/236/commits/7f0c59779d6b8f839353d52c8f2424d4e17155bb).

**Pull request merged**
