### PR TITLE
Fix sharedData fetching to use root-relative url

### PR DESCRIPTION
**Pull request by krzysztof-pyrzyk-ah**
## Description
Fetching static data was only working for `/` path, because it wasn't using root-relative url.
When opening a page with URL like f.ex `/blog/my-blog-post/`, which is using shared data, react-static is trying to fetch these data from `blog/my-blog-post/staticData/xxxxxxx.json`, but staticData folder is located at the root level of our page, so request should be prefixed with `/`.

## Changes/Tasks
- [x] Moved staticDataPath to a separate variable
- [x] Fixed fetching sharedData by using an URL with leading slash
- [x] Removed unnecessary space in PR's template

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by bram-l** [comment]
@tannerlinsley Did you have a look at this? I've been testing this thoroughly on my locale setup and it seems this would be the last fix to resolve the shared data issues (which is currently a blocker for us)

**Comment by krzysztof-pyrzyk-ah** [comment]
@bram-l Thanks for testing my pull request. For sure it fixes some issues, but honestly I still struggle with sharedData on `build` command.

**Comment by bram-l** [comment]
@krzysztof-pyrzyk-ah Did you try using the master branch (which includes #1019)?

**Comment by krzysztof-pyrzyk-ah** [comment]
@bram-l This may be the case! I've been using newest tag, as I thought your PR was released. I'll try that. Thanks ;)

**Comment by krzysztof-pyrzyk-ah** [comment]
@tannerlinsley Can I please ask for a Code Review? It's been a long time since this PR was created and the problem it solves hasn't been fixed anywhere else.

**Comment by tannerlinsley** [comment]
So what would happen if the asset path was set by the user to something like `https://cdn.com/mybucket`? Wouldn't this produce an invalid link? eg. `/https://cdn.com/mybucket`?

**Comment by krzysztof-pyrzyk-ah** [comment]
@tannerlinsley Good point, it would produce an invalid link. Haven't thought about that.
I'll have to come up with a new solution.
I'll take a look at `pathJoin` method cause asset path is by default set to `/` which is fine, but `pathJoin` method cleans leading slash by default.

**Comment by bram-l** [comment]
Yes that's right, I also didn't think about that... It looks like `makePathAbsolute` might come handy here!

**Comment by tannerlinsley** [comment]
Nice work!

**Pull request merged**
