### PR TITLE
[WIP] Babel 7, tree shaking

### PR DESCRIPTION
**Pull request by EmilTholin**
_The current versions of the `@babel` packages and `@std/esm` gives rise to a `TypeError: require(...).default is not a function`. It is probably a good idea to wait for `@babel` to come out of beta, since the combination of `@babel` packages and `@std/esm` breaks between minor changes._ 

This PR moves to Babel 7, moves away from `commonjs` to ES6 with `esm` to allow for tree shaking, and replaces the deprecated `latest` preset with the `env` preset.

[react-hot-loader](https://github.com/gaearon/react-hot-loader/blob/master/CHANGELOG.md) got support for Babel 7 in `3.1.2`, and it's working great! However, they removed `RedBox` as default error catcher in `3.0.0`, so the examples will no longer have that nice error in the browser, only in the console. The [`AppContainer` has to be changed to this to keep the functionality](https://github.com/gaearon/react-hot-loader#adding-a-custom-error-reporter).

[`@babel/preset-env` also got the super cool feature of `useBuiltIns: 'usage'` in Babel 7](https://github.com/babel/babel/tree/master/experimental/babel-preset-env#usebuiltins), but there is currently no way to customize the `moduleName`, so it looks for the polyfills relative to the user's folder and crashes, so this has to be added at a later stage (if at all).

Since both environments now use ES6, there is really no reason for the `watch` and `build` commands. `bin/react-static` could be changed to `require('../src/commands/index').default()` and `package.json.main` to `src/index.js`, but this would be a breaking change since e.g. `'react-static/lib/webpack/rules'` would be changed to `'react-static/src/webpack/rules'`, so that is probably best saved for the next major version (if it should be changed at all).

### CODE REVIEW

**Comment by jeffvandyke** [comment]
What is with the no newline at the end of the files? Best practice is to have all lines of a text file end with a new line character, for many reasons, see <https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline>

**Comment by EmilTholin** [comment]
It's a WIP, i'll fix that later, thanks.

**Comment by JustFly1984** [comment]
Please add support of 'extract-hoc-compose/babel', 'extract-hoc/babel' plugins for correct HMR

**Comment by jeffvandyke** [comment]
Just wanted to say thanks for working on this change. That babel env preset should make future maintenance easier, and this is even now a great, well documented, straight-forward project that had everything I wanted for a small website, and I loved being able to adjust the webpack config to support custom loaders for certain file types.

**Comment by tannerlinsley** [comment]
🤘🤘🙏

**Comment by tannerlinsley** [comment]
🎤 Check. 1, 2, 1, 2. What's the status here?

**Comment by ryami333** [comment]
@tannerlinsley Babel 7 isn't out of Beta yet

**Comment by tannerlinsley** [comment]
:(

**Pull request closed without merging**
