### PR TITLE
Material UI with JSS example

### PR DESCRIPTION
**Pull request by izziaraffaele**
Add Material UI with JSS server-side integration.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Hey, I'll merge this if we can get it up to speed with the new 5.0.0 version. :)

**Comment by skirunman** [comment]
I'd be interested in using this example.

Did notice you have bad link to Material UI github repo, should be https://github.com/mui-org/material-ui and not https://github.com/ant-design/ant-design

**Comment by izziaraffaele** [comment]
@skirunman README.md updated
@tannerlinsley I'm pretty busy right now but I can try to do something about it in 2 weeks

**Comment by tannerlinsley** [comment]
Thanks!

**Pull request merged**
