### PR TITLE
Add copy explaining the difference between automatic routing and cust…

### PR DESCRIPTION
**Pull request by Nembus**
…om route configuration.

 
 ### Is this a bug report?
 
 (write your answer here)
 
 
 
 ### Environment
 
 
 
 1. `react-static -v`: 
 2. `node -v`:
 3. `yarn --version or npm -v`:
 
 Then, specify:
 
 1. Operating system:
 2. Browser and version (if relevant):
 
 
 ### Steps to Reproduce
 
 
 
 (Write your steps here:)
 
 1. 
 2. 
 3. 
 
 
 ### Expected Behavior
 
 
 
 (Write what you thought would happen.)
 
 
 ### Actual Behavior
 
 
 
 (Write what happened. Please add screenshots!)
 
 
 ### Reproducible Demo
 
 
 
 (Paste the link to an example project and exact instructions to reproduce the issue.)

### CODE REVIEW

**Comment by Nembus** [comment]
Which ones? In the README?

**Comment by tannerlinsley** [comment]
The encoding in the readme was set to ISO-8859-1 for some reason.  Just fixed it though.

**Comment by Nembus** [comment]
Ha. My Webstorm has changed the encoding it seems. Sorry.

**Comment by tannerlinsley** [comment]
No worries.

**Pull request merged**
