### PR TITLE
hotfix/webpack-rebuilds

### PR DESCRIPTION
**Pull request by cgmx**
Hotfix for #124 implemented:
See: /src/webpack.js:#L63 and /src/static.js#L314 on this branch for more information.

No integration tests have been added yet, however this test works very well and does NOT increase build times.

Steps to test:

```
yarn build  <-------- Inside react-static/
cd ../
react-static/bin/react-static create
<<Make Basic Project>>
cd my-static-site/

vim project.json
<<Modify: "start" statement to location of react-static/bin/react-static>>
:wq

yarn start
```

### CODE REVIEW

**Comment by cgmx** [comment]
CLI Output after Hotfix impl: 

```
❯ yarn start
yarn run v1.2.1
$ <path-to-react-start>/react-static/bin/react-static start

=> Copying public directory...
=> [✓] Public directory copied: 1.253ms
=> Building Routes...
=> [✓] Routes Built: 719.381ms
=> Building App Bundle...
=> [✓] Build Complete: 3087.141ms
=> [✓] App serving at http://localhost:3000
```

**Comment by SShrike** [comment]
Are all the changes to the package.json, .babelrc, etc. really needed? They don't seem to be used to by anything, perhaps you commited them on accident.

**Comment by tannerlinsley** [comment]
Fantastic! Good to merge?

**Comment by cgmx** [comment]
Yup. I've finished up commits on my end. Good to merge, @tannerlinsley. 😄

**Pull request merged**
