### PR TITLE
Fix TypeScript definitions for Routes & add withRouteData & withSiteData

### PR DESCRIPTION
**Pull request by bwallberg**
## Description
Updated `index.d.ts` so that you can compile the react-static typescript template when using specific parts of the API.

## Changes/Tasks

* Fixed invalid typescript definitions for Routes ( it's actually not for Routes but is rather hijacked by @reach/router, but that's just how it works it seems...).

* Added missing typescript definitions for `withRouteData` & `withSiteData`

- [x] Changed code

## Motivation and Context
Fix broken typescript definitions

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by sw-yx** [comment]
i swear i PR'ed this before but something went wrong. thank you!

**Comment by julesce** [comment]
Thanks for hooking up this fix! Just for planning purposes, is there a rough date in mind for the next versioned release?

**Comment by sw-yx** [comment]
up to @tannerlinsley

**Comment by tannerlinsley** [comment]
Maybe someone should set up automated releases ;)

**Comment by tannerlinsley** [comment]
I'm supes busy right now, but I'll try and find some time to go through things soon.

**Comment by jaridmargolin** [comment]
Would be great to see this land in a release 😬

**Comment by julesce** [comment]
I know you guys are busy at the moment, but it'd be fabulous to see a release for the current `master` branch, since this is a pretty important fix that I'm sure most TypeScript users out there will be waiting for. As always, thanks for all your effort :-)

**Pull request merged**
