### PR TITLE
Example of using Prismic headless data

### PR DESCRIPTION
**Pull request by kildareflare**
### Is this a bug report?
 No

Contains an example of how to fetch data from Prismic headless browser.
Update Readme with a link to my personal site, built with react-static and Prismic. (requested by @tannerlinsley :0)   )

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Fantastic!!!

**Comment by tannerlinsley** [comment]
Let's get it passing the linter and I'll merge

**Comment by kildareflare** [comment]
@tannerlinsley Hey, I just tried creating another site using this as a template; but it did not come up in the list of templates. As I understood it, it should just get added to the list auto-magically...

>Can't find an example? We invite you to write one! Simply copy the basic or blank templates and make the necessary changes. Then submit a PR including your new example directory and a new item in the list above. When merged, your example will automatically become a template in the CLI. How magical!

Did I miss something?

**Comment by tannerlinsley** [comment]
Have you upgraded your global install of react static?

**Comment by kildareflare** [comment]
Nope. 😊 
Yup, updated and there it is. Sorry about that.

**Comment by tannerlinsley** [comment]
No worries :)

**Pull request merged**
