### PR TITLE
Remove webpack-dev-server/client from entry

### LINKED ISSUE #1109: [Bug] Local development server broken
I'm [noticing](https://spectrum.chat/react-static/general/broken-dev-builds-react-static-v6-3-x-and-7-0-x~8e1ac78a-d23f-406c-be05-57010f04368c) that fresh installs of React Static displays an empty page in develop mode (`$ react-static start`) and the console outputs `SyntaxError: The URL 'http:/[http//localhost]:300' is invalid` from SockJS. This occurs after running yarn upgrade in a previously working repo in either RS 6.3.x or 7.0.x. Seems that this is related to the 3.3.0 update of webpack-dev-server ([possibly this change?](https://github.com/webpack/webpack-dev-server/pull/1664)).

Adding this to my project's package.json and reinstalling dependencies fixes development builds. This confirms that something is borked in an update of webpack-dev-server.
```
"resolutions": {
  "react-static/webpack-dev-server": "~3.1.10"
}
```
### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Memory: 228.44 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    react-ga: ^2.5.7 => 2.5.7 
    react-markdown: ^4.0.6 => 4.0.6 
    react-moment: ^0.8.4 => 0.8.4 
    react-static: ^7.0.7 => 7.0.7 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0
```

### Steps to Reproduce the problem

1.  `npx react-static create`
2.  create site and cd in
3.  `yarn upgrade` to install latest dependencies
4.  `yarn start`
5.  navigate to `http://localhost:3000`
6.  See broken site? Open console.

### PR DESCRIPTION
**Pull request by SleeplessByte**
## Description

According to the [webpack-dev-server documentation](https://webpack.js.org/guides/hot-module-replacement/ ), the client should not be an entry. It seems to be an old way of configuring (I found this [article from 2016](https://medium.com/@rajaraodv/webpacks-hmr-react-hot-loader-the-missing-manual-232336dc0d96) that shows the client as an entry point).

When this line is present, the webpack-dev-server is actually required _twice_, as you can see in the following image:

1. once from the entry (`'webpack-dev-server/client?...'`)
2. once from the plugin (`'../../webpack-dev-server/client?...'`)

This would normally not be an issue. Identical requires are only executed once. However, `webpack-dev-server` as a plugin expects you to write:
```javascript
devServer: {
  host: 'hostname-without-scheme',
  port: number
}
```
And the manual `entry` expects you to write:
```javascript
devServer: {
  host: 'http://hostname-without-scheme',
  port: number
}
```
This results in two unique requires.

This might be a change they made recently, this might be a cross-env issue. I'm not certain. When this line is removed from the configuration, the HMR plugin correct _injects_ this entry into the configuration, only once.

Fixes #1109 

## Changes/Tasks

- [x] Changed code

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I have updated the documentation accordingly
- [X] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
It appears that even after this change, I am seeing 2 versions of `only-dev-server` and `dev-server`. Not sure where they're coming from yet, but man... I hate hot-reloading.

**Comment by SleeplessByte** [comment]
@tannerlinsley that's correct, that's a different "issue". It's probably because you explicitely added `'webpack/hot/only-dev-server'`, which I don't know about yet :)

I'll read about that next if you'd like and submit another PR.

**Comment by tannerlinsley** [comment]
Ah. I added it because it's mean to override the standard dev server code and not reload the page when things error. It's primarily for supporting things like react-hot-loader that offer inline-reloading of components.

**Comment by SleeplessByte** [comment]
Got it! I think it's fine (for now) to have both `only-dev-server` and `dev-server`, but IIRC, with webpack four, `dev-server` _should_ be able to support all that.

**Comment by dgavara** [comment]
@tannerlinsley When are you releasing the new version of react-static?

**Comment by tannerlinsley** [comment]
Still waiting on some changes to play out on master with hot-reloading. Soon.

**Comment by SleeplessByte** [comment]
Hey @tannerlinsley. Finally found something sane in the [documentation](https://webpack.js.org/configuration/dev-server/#devserverhot). Combine that with [this](https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr).

In other words: 
- I think you can remove the `hot/only-dev-server` line, and rely on `hotOnly: true` to provide it. Leave the plugin in.
- This means `hot: true` is **incorrect**.

**Comment by tannerlinsley** [comment]
So remove `hot: true` and add `hotOnly: true`?

**Comment by SleeplessByte** [comment]
Not at my regular machine, so have not tested.

Remove these:

- https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/webpack.config.dev.js#L26

- https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/runDevServer.js#L84

- Add `hotOnly: true`.

Leave everything else the same.

Can you try that out and see if it works as expected? ❤️

**Comment by tannerlinsley** [comment]
I'm on it.

**Comment by SleeplessByte** [comment]
FYI, I'm trying to match [this official configuration](https://webpack.js.org/guides/hot-module-replacement/#enabling-hmr) , but then using the `hotOnly` option 💯

**Comment by tannerlinsley** [comment]
Just tried it an hot-reloading fails silently during runtime. Nothing is triggered.

**Comment by tannerlinsley** [comment]
This is what I have so far:

- `hot: true`
	- injects the hot dev client into the browser
	- shows a single listener
    - hot-reloading events are not receieved in the browser
    - hot reloading doesn't work
- `hotOnly: true`
	- same as previous
- `hot:true, hotOnly: true`
	- same as previous
- Adding `webpack/hot/only-dev-server` to any of the above configurations:
	- injects the hot dev client into the browser
	- injects the hotOnly dev client into the browser
    - show 2 listeners
    - hot-reloading events are received in the browser
    - hot reloading works

**Comment by tannerlinsley** [comment]
I think I know what is happening here:

- `hotOnly` is working correctly in webpack dev server
Screen Shot 2019-04-24 at 3 48 08 PM
- Unfortunately, it's using `require.resolve`. Because of this, there end up being 2 different versions/instances of the client, so when the hot events come in to the browser, one instance is receiving them, but has no subscriptions, and the other instance that has the subscription doesn't receive the events. 

If webpack-dev-server's code doesn't use `require.resolve` it works perfectly. Clearly that's not an option (I doubt they would accept a PR like that), so from the other end, I want to figure out which module is trying to import stuff from the webpack-dev-server and instantiating it again. Maybe react-hot-loader?

**Comment by SleeplessByte** [comment]
Ah, so https://github.com/nozzle/react-static/pull/1135#issuecomment-486437870 means that the first two options _do_ work correctly if it weren't using `require.resolve`?

> one instance is receiving them, but has no subscriptions, and the other instance that has the subscription doesn't receive the events.

This makes sense that this would be the issue -- 

Why doesn't `require.resolve` work? As in, can't we just use that as well?

**Comment by SleeplessByte** [comment]
`react-hot-loader` should probably be used _on top_ of hotOnly, right?

**Comment by tannerlinsley** [comment]
Yes. I don't even know if it's RHL's fault. Something is resolving to a separate copy of the dev server code and not syncing up on the socket instance.

**Comment by tannerlinsley** [comment]
Here, you can see webpack emitting a hot-reload event through the emitter module:
Screen Shot 2019-04-25 at 10 24 28 AM
And here, you can see where that event is meant to be received and trigger a `check` (which is what would eventually lead to `hot.module.check/accept` calls running: Screen Shot 2019-04-25 at 10 24 50 AM

Unfortunately, the underlying emitter is not the same instance between the two, so they never communicate.

**Comment by tannerlinsley** [comment]
This could even be due to the dev environment of react-static. When npm-linked, webpack (which is running from within react-static files) will resolve to dependencies within react-static instead of the linked project. It's very possible that this isn't even a problem in actual projects that aren't npm-linked, but I don't want that to be an excuse for this not working. We should be able to develop in react-static and on linked projects seamlessly.

Maybe an alias to resolve any emitter imports to the same file would be a good idea?

**Comment by SleeplessByte** [comment]
> This could even be due to the dev environment of react-static. When npm-linked, webpack (which is running from within react-static files) will resolve to dependencies within react-static instead of the linked project. It's very possible that this isn't even a problem in actual projects that aren't npm-linked, but I don't want that to be an excuse for this not working. We should be able to develop in react-static and on linked projects seamlessly.

I wholeheartedly agree with you! This should work regardless of the environment. 

> Maybe an alias to resolve any emitter imports to the same file would be a good idea?

If that solves this for now, then sure! I'd rather have less duplication / 2 servers running.

**Comment by SleeplessByte** [comment]
https://github.com/nozzle/react-static/pull/1135#issuecomment-486743734

Is this in the same directory? because then it's indeed not the same path.

**Comment by tannerlinsley** [comment]
Figured it out. An alias in dev mode to resolve `webpack/hot/emitter` to the same module does the trick!

**Pull request merged**
