### PR TITLE
tweak startup perf by JSON.parse routeInfo

### PR DESCRIPTION
**Pull request by digitalkaoz**
see https://twitter.com/HenrikJoreteg/status/1143953338284703744

## Description

routeInfo is passed as json string and evaluated as JSON at runtime (which should increase the startup performance)

## Changes/Tasks

- [x] Changed code

## Motivation and Context

performance is always an issue ;)

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by digitalkaoz** [comment]
im having some weird errors, will investigate

**Comment by digitalkaoz** [comment]
I tested it with one of my projects, it worked fine. As it doesnt have many routes and stuff the performance gain wasnt huge, but i guess it comes in handy for bigger projects

**Comment by sw-yx** [comment]
indeed. this is the kind of simple optimization that we should build in.

**Comment by tannerlinsley** [comment]
Fantastic!

**Pull request merged**
