### PR TITLE
build: Reconfiguring Webpack for less variation between Prod and Dev.  

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
## Description
Dont hash JS & CSS in dev -  breaks HMR
Dont use `ClientCssHash` - internally managed via new css chunk plugin & enable HMR
Aggressive Code Splitting by default in Prod
`hash` not `chunkHash` for output.filename - its not a chunk

## Changes/Tasks

- [x] Initial Webpack 4 upgrade
- [ ] Optimize build
- [ ] Update plugins
- [ ] Refactor webpack config

## Motivation and Context
Time to upgrade to Webpack 4

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Short and sweet, first pass

**Comment by tannerlinsley** [comment]
Looks like some snapshots need to be looked at. If they are correct, they need to be updated. You can do that by running `yarn unitTestWatch`.

**Comment by tannerlinsley** [comment]
I'm too excited for this, so I'm merging. I'll handle the errors in master :)

**Comment by ScriptedAlchemy** [comment]
Omg tanner 😂 merged with errors 

Glad to been of service fellas ♥️ Hit me up anytime for some more fun

**Pull request merged**
