### PR TITLE
Add the plugin to the sass example

### LINKED ISSUE #228: The Sass test example is missing the plugin
Get an error for when testing the sass example.
image

I have the solution and will push a quick fix PR

### PR DESCRIPTION
**Pull request by talves**
### Is this a bug report? 

Yes
 
Fixes and closes #228

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Hold on. Why is this needed if we already have https://github.com/nozzle/react-static/blob/master/src/webpack/webpack.config.prod.js#L34?

**Comment by talves** [comment]
That is a very good question. Let me see if I can see the reason it is not being recognized.

**Comment by talves** [comment]
@tannerlinsley It also works if I change the code to:

`config.plugins = config.plugins`

something weird here on windows maybe?

**Comment by tannerlinsley** [comment]
Yeah I don't see why it wouldn't work without it.

**Comment by talves** [comment]
It works fine for the build, but does not on start, so it seems like a devServer issue. I will have to come back to it when I have some time.

**Comment by tannerlinsley** [comment]
Well that would mean it's something to do with the style loader then,
right? No styles are extracted in dev anyway, right?

**Comment by talves** [comment]
Ok, the reason it is loading for `prod` is because you were right above the plugin is being added in the `webpack.config.prod.js`
For `dev` it is **NOT** as you can see here https://github.com/nozzle/react-static/blob/master/src/webpack/webpack.config.dev.js#L34-L47
The plugin is then missing when we run the devServer (`stage === 'dev'`) with this configuration for the sass example.

I fixed this PR the way I would like to see it loading.

The question is: Are you going to maintain a sass rule in the core webpack config?

**Comment by talves** [comment]
I am not sure if this has been tested, but fixing the error does not fix the production build.
Am I the only one who sees the webpack being called twice for the configs? If you run a build on the basic example, two sets of styles get created, although this is not causing the issue here.

**Comment by chrisfo** [comment]
Could even be done a little like this (a little cleaner?):
```javascript
          {
            test: /\.s(a|c)ss$/,
            use: (stage === 'prod') ?
                ExtractTextPlugin.extract({
                  fallback: 'style-loader',
                  use: [
                    {                    
                      loader: 'css-loader',
                      options: {
                        minimize: true,
                        sourceMap: false
                      }
                    },
                    {
                      loader: 'sass-loader'
                    }                  
                  ]
                })
                :
                [
                  {loader: 'style-loader'},
                  {loader: 'css-loader'},
                  {loader: 'sass-loader'}
                ] 
          },

```

**Comment by tannerlinsley** [comment]
I just pushed some changes.  Let me know what you think.

**Comment by talves** [comment]
Yep, that would work.

**Comment by tannerlinsley** [comment]
Important to note here that you need to use the `stage` variable.

**Comment by talves** [comment]
I was thinking about that when I did the comment above, but thought it was directly tied to `process.env.NODE_ENV === 'development'`.

Good to know, Thanks.

**Pull request merged**
