### PR TITLE
Break up static index to be more modular

### PR DESCRIPTION
**Pull request by jasonlafferty**
## Description

This PR pulls out the components from the static index file and adds some snapshot test around them. It breaks up the functions in the static index file. 

Also, add comments to recurseCreateNormalizedRoute as it is a complicated function.

## Types of changes

- [x] Refactoring/add tests (refactoring or adding a test which isn't a fix or add a feature)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] My changes have tests around them

### CODE REVIEW

**Comment by sudarshang** [comment]
I spent a lot of time working with the static/index.js while trying to upgrade to webpack-4. Refactoring it to make it more modular is great!

**Comment by jasonlafferty** [comment]
Yeah, I have more time on Monday to probably finish this, will rebase.

**Comment by jasonlafferty** [comment]
@tannerlinsley think this should be fine to merge, unsure why that last test failed?

**Comment by jasonlafferty** [comment]
I think I know.

**Pull request merged**
