### PR TITLE
Error overlay

### PR DESCRIPTION
**Pull request by sghall**
Hey.  Checking out react-static for updating the react-move docs. This PR adds the error overlay used in create-react-app.  Fix for https://github.com/nozzle/react-static/issues/20.

### CODE REVIEW

**Comment by zsherman** [comment]
@sghall been meaning to make a bunch of updates to [react-story](https://github.com/react-tools/react-story), maybe we should port some of the components into that?

**Comment by sghall** [comment]
Hey, @zsherman.  Right on.  I'm fine using react-static or react-story.  Just like to simplify the docs on react-move.

**Comment by zsherman** [comment]
@sghall absolutely, maybe we should chat in the slack channel quickly so I can make sure I give you the tools you need there.

**Comment by tannerlinsley** [comment]
You guys can use both... :)

**Comment by tannerlinsley** [comment]
Hey, I accidentally broke this PR, no changes really, just a file location change. Do you want to fix it up?

**Comment by sghall** [comment]
Looks good to go.

**Pull request merged**
