### PR TITLE
WIP add custom error page

### PR DESCRIPTION
**Pull request by kildareflare**
I thought it would be nice to have a custom error page, for production in particular and that it could work in a similar manner to the 404 page.
I've made a start on this but had to move onto something else. I'll pick it up again shortly.
One thing I was not sure about was how to actually switch in the custom page. Initially I thought this could be done on line 682 of index.js - but could not find an obvious way of doing this. 

Any ideas?

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This leans me towards getting rid of the is404 flag and just having users define a 404 route. Then it's ready enough to allow them to define a 500 route as well.

**Comment by tannerlinsley** [comment]
Concerning the catching of the error, you would simply push the location to 500 using react routers history API.

**Comment by tannerlinsley** [comment]
Moving this PR to "stalled" status.  This is still a cool idea we can keep discussing.

**Comment by kildareflare** [comment]
Hey, this is still on my todo list, got swamped lately. I'll get back to it soon hopefully.

**Pull request closed without merging**
