### PR TITLE
Update babel config to get Hot Reloading working on Routes

### PR DESCRIPTION
**Pull request by blesswinsamuel**
## Description

Hot Reloading is not working in the current version 5.9.7. Making this change gets Hot Reloading working for Routes in the project I'm working on.

## Changes/Tasks

- [ ] Changed code

## Motivation and Context

https://github.com/nozzle/react-static/issues/616

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by blesswinsamuel** [comment]
Apparently, this doesn't work on restarting the dev server. Closing this PR for now.

**Comment by Dragomir-Ivanov** [comment]
What is the resolution if this issue? Latest stable 5.9.7 still has no HMR working. 
@blesswinsamuel If you have some solution, please share.

**Comment by alukaszew** [comment]
I've stopped my own project because of this issue. Is there any chance to fix it somehow? Anybody?

**Comment by cbejensen** [comment]
See https://spectrum.chat/thread/ae84f81d-0cfb-48ea-8663-de702ff9afb0?m=MTUzNDkzOTczMzMyNA==

It was recommended to change .babelrc to this:

    {
      "extends": "react-static/.babelrc",
      "plugins": [
        "react-hot-loader/babel"
      ]
    }

Worked for me.

**Comment by alukaszew** [comment]
@cbejensen , It starts to work after remove `node_modules,` edited `.babelrc ` as you recommended, then `npm install`. Thanks for advice!

**Pull request closed without merging**
