### PR TITLE
Add switch to the Routes component to disable force update on location change. 

### PR DESCRIPTION
**Pull request by georgehenderson**
This PR adds a switch to the Routes component to disable force update on location change. This is useful for cases where you bring your own router and don't need the Routes component to force an update with url changes.

## Description
Adds a new default prop `disableUpdateOnLocationChange: false`

## Changes/Tasks
- [x] New default prop `disableUpdateOnLocationChange: false`

## Motivation and Context
The Routes component causes the next page to mount twice when inside a Reach Router. This can lead to bugs when doing working in `componentDidMount` like logging analytics. 
The router setup for reference
```javascript
<Router>
  <Routes default />
</Router>
```

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by georgehenderson** [comment]
@tannerlinsley Does opting out of this behavior for use with reach make sense and align with the direction your heading? I know you mentioned you were toying with a hook based router.

**Comment by tannerlinsley** [comment]
I mostly wondering if we could get around this without adding any more api surface area, eg. find a core fix that just works invisibly. Can you point me to some code where you are experiencing the need for this?

**Comment by georgehenderson** [comment]
Yeah ideally we shouldn't add more api surface area. Here is a codesandbox that demonstrates the problem through logs. https://codesandbox.io/s/o1oj410l5y .  Not sure why errors are being thrown in the sandbox but the code works if you pull it down.

**Comment by georgehenderson** [comment]
The blog page and post page templates have logs that will double log on page change

**Comment by tannerlinsley** [comment]
I believe this is now solved from #1015.

**Pull request closed without merging**
