### PR TITLE
Added example where Progressive Web App is enabled by default

### PR DESCRIPTION
**Pull request by muloka**
Using the glamorous example as a base, created a pwa-glamorous example where Progressive Web App features are enabled by default.

See issue #196

### CODE REVIEW

**Comment by tannerlinsley** [comment]
So what's next here?  What's the state of this PR?

**Comment by tannerlinsley** [comment]
Going to close this for now.  Would love to see this work out though!

**Comment by danielemesh** [comment]
Anything new here?
There is no PR or a PWA example...

**Comment by tannerlinsley** [comment]
I would love to see activity here too.  Might be easier after v5 lands...

**Comment by danielemesh** [comment]
@tannerlinsley what is planned for v5?

**Comment by tannerlinsley** [comment]
Take a look at the changelog here
https://github.com/nozzle/react-static/blob/master/CHANGELOG.md

**Comment by spences10** [comment]
Is this useable?

I'll give it a try and let you know how I get on...

**Comment by spences10** [comment]
So I tried this and like with the other examples I have tried I get a `ReferenceError: window is not defined` which I think is a `node` thing but I don't know what the alternative is, think it's global 🤔

**Pull request closed without merging**
