### PR TITLE
Fixing hot reloading in examples

### PR DESCRIPTION
**Pull request by bassman365**
## Description

I created a couple of projects, one using the basic template and another using the animated-routes template.  Everything went great (I am really glad I found this project!)  but I noticed hot reloading was not working.
## Changes/Tasks

- [x] Added react-hot-loader/babel plugin to root .babelrc file 
- [x] Added/updated the latest react-hot-loader dependency to the package.json file for each of the examples.

## Motivation and Context

Gets hot reloading working and addresses https://github.com/nozzle/react-static/issues/606

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This won't be necessary in v6. Have you tried using master?

**Comment by bassman365** [comment]
I just tried that and ran into some issues:


Here is what I did:
cloned repo:
yarn install
yarn run build
from \react-static\bin directory, ran: node .\react-static create
ran through the prompts selecting basic template
watched it yarn install
ran yarn start on the newly created project.
This was done on a Windows 10 machine
yarn 1.7
node v8.9.4

**Comment by cdock1029** [comment]
This is because the templates generate a `package.json` that depends on an older version of `react-static`

You have to manually change the local project dependency to *also* use version 6.. I ran into this too, took me a while to notice the discrepancy between cli / project versions..

**Comment by tannerlinsley** [comment]
Correct. The easiest way to do this during development is to use `yarn
link` in the react-static root and `yarn link react-static` in the example
directory to link the dependencies locally.

**Pull request closed without merging**
